version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - wget https://releases.hashicorp.com/terraform/1.7.3/terraform_1.7.3_linux_amd64.zip
      - unzip terraform_1.7.3_linux_amd64.zip -d /usr/binn
      - chmod +x /usr/bin/terraform
  build:
    commands:
      - ENV=$(echo ${CODEBUILD_BUILD_ID%%-*})
      - echo $ENV
      - terraform init --backend-config=non-prod.conf -reconfigure
      - terraform workspace select $ENV
      - terraform apply -parallelism=1 -auto-approve