name: release-to-prod
on:
  issue_comment:
    types: [created]
  pull_request_target:
    branches:
      - main
jobs:
  Log-Context:
    name: Log Context
    runs-on: ubuntu-latest
    steps:
      - name: log-context
        run: echo '${{ toJSON(github) }}'
  Pull-Request-Check:
    name: Pull development in main with Rebase
    runs-on: ubuntu-latest
    if: >-
      github.event.issue.pull_request != '' &&
      github.ref == 'refs/heads/development' &&
      (
        github.event.comment.author_association == 'COLLABORATOR' ||
        github.event.comment.author_association == 'CONTRIBUTOR'
      ) &&
      (
        contains(github.event.comment.body, '/rebaseMain')
      )
    steps:
      - uses: actions/checkout@v2

        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          ref: main
      - name: pull main
        run: git pull

      - name: Rebase main with development
        run: git pull --rebase origin development

      - name: Push main
        run: git push origin main
